name: Publish Package

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 安装 pnpm
      - uses: pnpm/action-setup@v3
        with:
          version: 9 # 建议固定版本，便于 CI 一致

      # 设置 Node 环境
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          # 如果你使用 pnpm + npm 发布，需要这一行让 npm token 生效
          always-auth: true

      # 安装依赖
      - run: pnpm install

      # 构建
      - run: pnpm run build

      # 测试（如果有）
      - run: pnpm test

      # 发布到 npm
      - run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
