name: Tag Release

on:
  push:
    branches:
      - main

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Get package.json version
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=v$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: check_tag
        run: |
          TAG=${{ steps.get_version.outputs.VERSION }}
          if git rev-parse $TAG >/dev/null 2>&1; then
            echo "Tag $TAG already exists, skipping tag creation."
            echo "SKIP=true" >> $GITHUB_OUTPUT
          else
            echo "Tag $TAG does not exist, proceeding to create."
            echo "SKIP=false" >> $GITHUB_OUTPUT
          fi

      - name: Create and push tag
        if: steps.check_tag.outputs.SKIP == 'false'
        run: |
          git config user.name "Jinming6"
          git config user.email "response965@163.com"
          git tag ${{ steps.get_version.outputs.VERSION }}
          git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Z-LabNext/ztool.git ${{ steps.get_version.outputs.VERSION }}
